# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic
# template used to generate migration file names; The default value
# is "%%(rev)s_%%(slug)s", but the "date" format is more suitable for our use case.
file_template = %%(year)d-%%(month).2d-%%(day).2d_%%(hour).2d.%%(minute).2d_%%(second).2d_%%(slug)s
# timezone to use when rendering the date
# stamp_date_format = %Y-%m-%d %H:%M%S
# sqlalchemy.url = driver://user:password@localhost/dbname
sqlalchemy.url = mysql+pymysql://root:password@localhost:3306/mydiary?ssl_disabled=true

[post_write_hooks]
# post_write_hooks defines scripts or commands which are run after each migration script is written
# e.g. "black": {"type": "console_script", "script_name": "black", "args": ["-l 79", "."]}
#      "isort": {"type": "console_script", "script_name": "isort", "args": ["--profile", "black", "."]}
# multiple hooks can be defined, and they will be executed in the order they appear in the config
tools = black, isort

[black]
type = console_script
script_name = black
args = ["-l 79", "."]

[isort]
type = console_script
script_name = isort
args = ["--profile", "black", "."]

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
